### ISSUE TITLE
Source file app.js

### ISSUE THREAD

**Issue by GENESIS-PLUS** [hammas1002/natal-chart#1]
Hello, thank you for your work, but I would like to supplement it a little, and is it possible to provide an file app.js in the source code?
I will be very grateful.

**Comment by hammas1002** [comment]
Hi there. The app.js file is already there with the rest of the files. Or am I missing something here?

**Comment by GENESIS-PLUS** [comment]
> Hi there. The app.js file is already there with the rest of the files. Or am I missing something here?

You have compressed it. 
I would like it without compression, it is difficult to understand the compressed code

**Comment by GENESIS-PLUS** [comment]
> Hi there. The app.js file is already there with the rest of the files. Or am I missing something here?

You have compressed it.
I would like it without compression, it is difficult to understand the compressed code

**Comment by hammas1002** [comment]
Okay. Added the uncompressed app.js file in the source code. I did not code it.
And this is the Node package it was actually taken from if you are interested.
https://github.com/0xStarcat/CircularNatalHoroscopeJS

**Comment by GENESIS-PLUS** [comment]
> Okay. Added the uncompressed app.js file in the source code. I did not code it. And this is the Node package it was actually taken from if you are interested. https://github.com/0xStarcat/CircularNatalHoroscopeJS

thank you)

**Comment by GENESIS-PLUS** [comment]
Hi, I found an interesting error, I don't understand what this is related to? if you set the date 01-01-2022 and the time 10-00, it gives an error. 
by the way, the date 02-01-2022 also gives an error, but 03-01-2022 already works without errors.
Do you have any thoughts?

Photo error
https://imgur.com/a/tbVzYSe

**Comment by hammas1002** [comment]
Problem seems to be with the function **createSunSign()**. Either the dates for Sun Signs are not set right (Line NO: 14393 - 14571) for **capricorn** and **sagittarius**, or **createSunSign()** function isn't working right somehow. As a result, it does not initialize **sunSign.Lable** of some object and keeps it undefined. Because of that on chart generation when **handleSubmit()** function runs, it tries to update the html element **sunSignElement** label with an undefined **sunSign.Lable** value, resulting in an error and preventing the program to proceed further.
I don't know how to solve this problem by fixing **createSunSign()** function so, I have just hardcoded **sunSignElement** text value in the case of **capricorn** and **sagittarius** where the problem was occurring and it's working fine now. (Line num: 15717).

**Comment by GENESIS-PLUS** [comment]
thank you for your decision
